{% set name = "qiskit-finance" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-finance-{{ version }}.tar.gz
  sha256: b22fc7e0f23837ee659d1dbe974f3d69ec0d291e51486a2ad81dcf17b4ad8a4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - certifi
    - nasdaq-data-link
    - urllib3
    - fastdtw
    - numpy >=1.17
    - pandas
    - psutil >=5
    - python >=3.7
    - qiskit-optimization >=0.2.0
    - qiskit-terra >=0.20.0
    - quandl
    - scikit-learn >=0.20.0
    - scipy >=1.4
    - setuptools >=40.1.0
    - yfinance >=0.1.70

test:
  imports:
    - qiskit_finance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-finance
  summary: 'Qiskit Finance: A library of quantum computing finance experiments'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
